<?php
require_once __DIR__.'/config.php'; require_once __DIR__.'/includes/functions.php'; $pageTitle='School Community'; require_role(['admin','teacher','student','parent']); require_once __DIR__.'/includes/header.php';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';try{
 if($action==='post'){
   if(user()['role']==='parent' && empty($_POST['allow_parent_post'])) throw new RuntimeException('Parents can participate in discussions but cannot publish school announcements.');
   $type=user()['role']==='admin'?'announcement':'discussion';$st=$pdo->prepare('INSERT INTO community_posts(author_id,title,body,post_type) VALUES(?,?,?,?)');$st->execute([user()['id'],trim($_POST['title']),trim($_POST['body']),$type]);audit($pdo,'create','community_posts',(int)$pdo->lastInsertId());flash('success','Post published.');
 }elseif($action==='comment'){$post=(int)$_POST['post_id'];$body=trim($_POST['body']);if($body==='')throw new RuntimeException('Comment cannot be empty.');$st=$pdo->prepare('INSERT INTO community_comments(post_id,author_id,body) VALUES(?,?,?)');$st->execute([$post,user()['id'],$body]);
 }elseif($action==='react'){$post=(int)$_POST['post_id'];$reaction=$_POST['reaction']??'like';$reaction=in_array($reaction,['like','helpful','celebrate'],true)?$reaction:'like';$st=$pdo->prepare('INSERT INTO community_reactions(post_id,user_id,reaction) VALUES(?,?,?) ON DUPLICATE KEY UPDATE reaction=VALUES(reaction),created_at=NOW()');$st->execute([$post,user()['id'],$reaction]);}
 redirect('community.php');}catch(Throwable $e){$error=$e->getMessage();}}
$posts=$pdo->query("SELECT p.*,u.full_name,u.role,(SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id) comments,(SELECT COUNT(*) FROM community_reactions r WHERE r.post_id=p.id) reactions FROM community_posts p JOIN users u ON u.id=p.author_id ORDER BY p.created_at DESC LIMIT 100")->fetchAll();$success=flash('success');
?><div class="d-flex justify-content-between align-items-center mb-3"><h2>School Community</h2></div><?php if($success): ?><div class="alert alert-success"><?=e($success)?></div><?php endif;?><?php if($error): ?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<?php if(user()['role']!=='parent'): ?><div class="card p-4 mb-4"><h5><?=user()['role']==='admin'?'Publish school announcement':'Start a discussion'?></h5><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="post"><div class="col-md-5"><input class="form-control" name="title" placeholder="Title" required></div><div class="col-12"><textarea class="form-control" name="body" rows="3" placeholder="Write your message..." required></textarea></div><div class="col-12"><button class="btn btn-primary">Publish</button></div></form></div><?php endif;?>
<?php foreach($posts as $p): ?><article class="card p-4 mb-3"><div class="d-flex justify-content-between"><div><h5 class="mb-1"><?=e($p['title'])?></h5><div class="small text-muted"><?=e($p['full_name'])?> · <?=e($p['role'])?> · <?=e($p['created_at'])?></div></div><span class="badge text-bg-<?=($p['post_type']==='announcement'?'primary':'secondary')?>"><?=e($p['post_type'])?></span></div><p class="mt-3 mb-3"><?=nl2br(e($p['body']))?></p><div class="d-flex gap-2 mb-3"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="react"><input type="hidden" name="post_id" value="<?=$p['id']?>"><input type="hidden" name="reaction" value="like"><button class="btn btn-sm btn-outline-primary">Like (<?=e((string)$p['reactions'])?>)</button></form><span class="small text-muted align-self-center"><?=e((string)$p['comments'])?> comments</span></div>
<div class="border-top pt-3"><h6>Conversation</h6><?php $cs=$pdo->prepare("SELECT c.*,u.full_name,u.role FROM community_comments c JOIN users u ON u.id=c.author_id WHERE c.post_id=? ORDER BY c.created_at ASC LIMIT 100");$cs->execute([$p['id']]);foreach($cs->fetchAll() as $c): ?><div class="border-bottom py-2"><strong><?=e($c['full_name'])?></strong> <span class="small text-muted"><?=e($c['role'])?> · <?=e($c['created_at'])?></span><div><?=nl2br(e($c['body']))?></div></div><?php endforeach;?><form method="post" class="mt-3"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="comment"><input type="hidden" name="post_id" value="<?=$p['id']?>"><div class="input-group"><input class="form-control" name="body" placeholder="Write a respectful comment..." required><button class="btn btn-outline-secondary">Comment</button></div></form></div></article><?php endforeach;?><?php require __DIR__.'/includes/footer.php';
