<?php
require_once __DIR__.'/../config.php'; require_once __DIR__.'/../includes/functions.php'; $pageTitle='Accounts'; require_role(['admin']); require_once __DIR__.'/../includes/header.php';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$role=$_POST['role'];$pdo->beginTransaction();try{
$st=$pdo->prepare("INSERT INTO users(username,password_hash,role,full_name,email,phone) VALUES(?,?,?,?,?,?)");$st->execute([trim($_POST['username']),password_hash($_POST['password'],PASSWORD_DEFAULT),$role,trim($_POST['full_name']),trim($_POST['email']??'')?:null,trim($_POST['phone']??'')?:null]);$uid=(int)$pdo->lastInsertId();
if($role==='parent'){$st=$pdo->prepare("INSERT INTO parents(user_id) VALUES(?)");$st->execute([$uid]);}
if($role==='student'){$st=$pdo->prepare("INSERT INTO students(user_id,admission_no,surname,firstname) VALUES(?,?,?,?)");$st->execute([$uid,trim($_POST['admission_no']),trim($_POST['surname']),trim($_POST['firstname'])]);}
$pdo->commit();$saved=true;
}catch(Throwable $e){$pdo->rollBack();$error='Account could not be created. Check that the username/email/admission number is unique.';}}
$rows=$pdo->query("SELECT id,username,full_name,role,email,phone,status,last_login_at FROM users ORDER BY id DESC")->fetchAll();
?><h2>User Accounts</h2><?php if(!empty($saved)): ?><div class="alert alert-success">Account created.</div><?php endif;?><?php if(!empty($error)): ?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<div class="card p-4 mb-4"><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>">
<div class="col-md-2"><label>Role</label><select class="form-select" name="role"><option>parent</option><option>student</option></select></div><div class="col-md-3"><label>Full name</label><input class="form-control" name="full_name" required></div><div class="col-md-2"><label>Username</label><input class="form-control" name="username" required></div><div class="col-md-2"><label>Password</label><input class="form-control" type="password" name="password" required></div><div class="col-md-3"><label>Email</label><input class="form-control" type="email" name="email"></div>
<div class="col-md-3"><label>Phone</label><input class="form-control" name="phone"></div><div class="col-md-3"><label>Admission No. (student only)</label><input class="form-control" name="admission_no"></div><div class="col-md-3"><label>Surname (student only)</label><input class="form-control" name="surname"></div><div class="col-md-3"><label>First name (student only)</label><input class="form-control" name="firstname"></div><div class="col-12"><button class="btn btn-primary">Create account</button></div></form></div>
<div class="card p-3 table-responsive"><table class="table"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Email</th><th>Status</th><th>Last login</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=e($r['full_name'])?></td><td><?=e($r['username'])?></td><td><?=e($r['role'])?></td><td><?=e($r['email'])?></td><td><?=e($r['status'])?></td><td><?=e($r['last_login_at'])?></td></tr><?php endforeach;?></tbody></table></div>
<?php require __DIR__.'/../includes/footer.php';