<?php
require_once __DIR__.'/../config.php'; require_once __DIR__.'/../includes/functions.php'; $pageTitle='Admissions'; require_role(['admin']); require_once __DIR__.'/../includes/header.php';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=(int)$_POST['id'];$status=$_POST['status'];try{$pdo->beginTransaction();$st=$pdo->prepare('SELECT * FROM admissions WHERE id=? FOR UPDATE');$st->execute([$id]);$a=$st->fetch();if(!$a)throw new RuntimeException('Application not found.');
if($status==='enrolled' && empty($a['enrolled_student_id'])){
 $temp=generate_temp_password();$admissionNo=next_registration_number($pdo,'student');$username='student.'.strtolower(str_replace('/','.',str_replace(' ','',$admissionNo)));$classId=null;if($a['applying_class']){$c=$pdo->prepare("SELECT id FROM classes WHERE CONCAT(name,' ',COALESCE(section,''))=? OR name=? LIMIT 1");$c->execute([$a['applying_class'],$a['applying_class']]);$classId=$c->fetchColumn()?:null;}
 $st=$pdo->prepare("INSERT INTO users(username,password_hash,role,full_name,email,phone,must_change_password) VALUES(?,?,?,?,?,?,1)");$st->execute([$username,password_hash($temp,PASSWORD_DEFAULT),'student',trim($a['surname'].' '.$a['firstname'].' '.$a['othername']),null,null,1]);$uid=(int)$pdo->lastInsertId();
 $st=$pdo->prepare("INSERT INTO students(user_id,admission_no,surname,firstname,othername,gender,dob,class_id,phone,address,admission_date) VALUES(?,?,?,?,?,?,?,?,?,?,CURDATE())");$st->execute([$uid,$admissionNo,$a['surname'],$a['firstname'],$a['othername'],$a['gender'],$a['dob'],$classId,null,$a['address']]);$sid=(int)$pdo->lastInsertId();
 $pdo->prepare("UPDATE admissions SET status='enrolled',notes=?,enrolled_student_id=?,reviewed_at=NOW(),reviewed_by=? WHERE id=?")->execute([trim($_POST['notes']??''),$sid,user()['id'],$id]);$pdo->commit();audit($pdo,'enroll','admissions',$id,'Student '.$admissionNo.' enrolled');flash('success','Admission enrolled. Student registration number: '.$admissionNo.' | Username: '.$username.' | First password: '.$temp);redirect('admissions.php');
}
$pdo->prepare("UPDATE admissions SET status=?,notes=?,reviewed_at=NOW(),reviewed_by=? WHERE id=?")->execute([$status,trim($_POST['notes']??''),user()['id'],$id]);$pdo->commit();audit($pdo,'update','admissions',$id);flash('success','Admission updated.');redirect('admissions.php');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='Admission action failed: '.$e->getMessage();}}
$rows=$pdo->query("SELECT a.*,s.admission_no enrolled_no FROM admissions a LEFT JOIN students s ON s.id=a.enrolled_student_id ORDER BY a.submitted_at DESC LIMIT 500")->fetchAll();$success=flash('success');
?><h2>Admissions</h2><?php if($success): ?><div class="alert alert-success"><strong>Save credentials securely:</strong><br><?=e($success)?></div><?php endif;?><?php if($error): ?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="card p-3 table-responsive"><table class="table align-middle"><thead><tr><th>Application</th><th>Applicant</th><th>Parent</th><th>Class</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=e($r['application_no'])?></td><td><?=e(trim($r['surname'].' '.$r['firstname'].' '.$r['othername']))?></td><td><?=e($r['parent_name'].' / '.$r['parent_phone'])?></td><td><?=e($r['applying_class'])?></td><td><?=e($r['status'])?><?=($r['enrolled_no']?' · '.e($r['enrolled_no']):'')?></td><td><?php if(!$r['enrolled_student_id']): ?><form method="post" class="d-flex gap-2"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><select class="form-select form-select-sm" name="status"><option value="submitted">submitted</option><option value="under_review">under review</option><option value="accepted">accepted</option><option value="rejected">rejected</option><option value="enrolled">enroll & register</option></select><input class="form-control form-control-sm" name="notes" placeholder="Notes"><button class="btn btn-sm btn-primary">Save</button></form><?php else: ?><span class="text-success">Registered</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php require __DIR__.'/../includes/footer.php';
