<?php
require_once __DIR__.'/../config.php'; require_once __DIR__.'/../includes/functions.php'; $pageTitle='School Settings'; require_role(['admin']); require_once __DIR__.'/../includes/header.php';
$ok=$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();
    $name=trim($_POST['school_name']); $code=strtoupper(preg_replace('/[^A-Z0-9]/','',trim($_POST['school_code']))); if($name===''||$code===''){$err='School name and school code are required.';} else {
        $logo=setting($pdo,'logo');
        if(isset($_FILES['logo']) && $_FILES['logo']['error']===UPLOAD_ERR_OK){
            if($_FILES['logo']['size']>2*1024*1024){$err='Logo must be 2MB or smaller.';} else { $mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['logo']['tmp_name']); $allowed=['image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp']; if(!isset($allowed[$mime])){$err='Logo must be PNG, JPG or WEBP.';} else {$dir=__DIR__.'/../uploads'; if(!is_dir($dir)) mkdir($dir,0750,true); $file='school_logo_'.bin2hex(random_bytes(8)).'.'.$allowed[$mime]; move_uploaded_file($_FILES['logo']['tmp_name'],$dir.'/'.$file); $logo='uploads/'.$file;}}}
        if($err===''){ $st=$pdo->prepare('UPDATE settings SET school_name=?,school_code=?,school_email=?,school_phone=?,school_address=?,logo=?,email_enabled=?,email_from=?,sms_enabled=?,sms_endpoint=?,sms_api_key=?,sms_sender_id=?,whatsapp_enabled=?,whatsapp_endpoint=?,whatsapp_token=?,whatsapp_phone_number_id=? WHERE id=1'); $st->execute([$name,$code,trim($_POST['school_email'])?:null,trim($_POST['school_phone'])?:null,trim($_POST['school_address'])?:null,$logo,(int)isset($_POST['email_enabled']),trim($_POST['email_from'])?:null,(int)isset($_POST['sms_enabled']),trim($_POST['sms_endpoint'])?:null,trim($_POST['sms_api_key'])?:null,trim($_POST['sms_sender_id'])?:null,(int)isset($_POST['whatsapp_enabled']),trim($_POST['whatsapp_endpoint'])?:null,trim($_POST['whatsapp_token'])?:null,trim($_POST['whatsapp_phone_number_id'])?:null]); audit($pdo,'update','settings',1);$ok='School settings saved.'; }
    }
}
$s=$pdo->query('SELECT * FROM settings WHERE id=1')->fetch();
?><h2>School Settings</h2><?php if($ok): ?><div class="alert alert-success"><?=e($ok)?></div><?php endif;?><?php if($err): ?><div class="alert alert-danger"><?=e($err)?></div><?php endif;?><div class="card p-4"><form method="post" enctype="multipart/form-data" class="row g-3"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>">
<div class="col-md-6"><label>School name</label><input class="form-control" name="school_name" value="<?=e($s['school_name'])?>" required></div><div class="col-md-3"><label>School code</label><input class="form-control" name="school_code" value="<?=e($s['school_code'])?>" maxlength="20" required><div class="form-text">Used in generated IDs.</div></div><div class="col-md-3"><label>School logo</label><input class="form-control" type="file" name="logo" accept="image/png,image/jpeg,image/webp"></div>
<div class="col-md-4"><label>Email</label><input class="form-control" type="email" name="school_email" value="<?=e($s['school_email'])?>"></div><div class="col-md-4"><label>Phone</label><input class="form-control" name="school_phone" value="<?=e($s['school_phone'])?>"></div><div class="col-md-4"><label>Address</label><input class="form-control" name="school_address" value="<?=e($s['school_address'])?>"></div>
<div class="col-12"><hr><h5>Notification channels</h5><p class="text-muted">Notifications are queued first. Configure your provider, then run <code>cron/notifications_worker.php</code> from a protected scheduled task.</p></div>
<div class="col-md-3"><div class="form-check"><input class="form-check-input" type="checkbox" name="email_enabled" <?=((int)$s['email_enabled']?'checked':'')?>><label class="form-check-label">Email enabled</label></div><input class="form-control mt-2" name="email_from" placeholder="From email" value="<?=e($s['email_from'])?>"></div>
<div class="col-md-5"><div class="form-check"><input class="form-check-input" type="checkbox" name="sms_enabled" <?=((int)$s['sms_enabled']?'checked':'')?>><label class="form-check-label">SMS enabled</label></div><input class="form-control mt-2" name="sms_endpoint" placeholder="SMS provider JSON endpoint" value="<?=e($s['sms_endpoint'])?>"><input class="form-control mt-2" name="sms_api_key" placeholder="API key" value="<?=e($s['sms_api_key'])?>"><input class="form-control mt-2" name="sms_sender_id" placeholder="Sender ID" value="<?=e($s['sms_sender_id'])?>"></div>
<div class="col-md-4"><div class="form-check"><input class="form-check-input" type="checkbox" name="whatsapp_enabled" <?=((int)$s['whatsapp_enabled']?'checked':'')?>><label class="form-check-label">WhatsApp enabled</label></div><input class="form-control mt-2" name="whatsapp_endpoint" placeholder="WhatsApp API endpoint" value="<?=e($s['whatsapp_endpoint'])?>"><input class="form-control mt-2" name="whatsapp_token" placeholder="API token" value="<?=e($s['whatsapp_token'])?>"><input class="form-control mt-2" name="whatsapp_phone_number_id" placeholder="Phone number ID" value="<?=e($s['whatsapp_phone_number_id'])?>"></div>
<div class="col-12"><button class="btn btn-primary">Save settings</button></div></form></div><?php require __DIR__.'/../includes/footer.php';
