<?php
require_once __DIR__.'/../config.php'; require_once __DIR__.'/../includes/functions.php'; $pageTitle='Students'; require_role(['admin']); require_once __DIR__.'/../includes/header.php';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();
 try{$pdo->beginTransaction();
   $surname=trim($_POST['surname']);$firstname=trim($_POST['firstname']);$other=trim($_POST['othername']??'');$admissionNo=next_registration_number($pdo,'student');$temp=generate_temp_password();
   $username='student.'.strtolower(str_replace('/','.',str_replace(' ','', $admissionNo)));
   $st=$pdo->prepare("INSERT INTO users(username,password_hash,role,full_name,email,phone,must_change_password) VALUES(?,?,?,?,?,?,1)");$st->execute([$username,password_hash($temp,PASSWORD_DEFAULT),'student',trim($surname.' '.$firstname.' '.$other),trim($_POST['email']??'')?:null,trim($_POST['phone']??'')?:null]);$uid=(int)$pdo->lastInsertId();
   $st=$pdo->prepare("INSERT INTO students(user_id,admission_no,surname,firstname,othername,gender,dob,class_id,phone,address,admission_date) VALUES(?,?,?,?,?,?,?,?,?,?,?)");$st->execute([$uid,$admissionNo,$surname,$firstname,$other,$_POST['gender']?:null,$_POST['dob']?:null,$_POST['class_id']?:null,trim($_POST['phone']??''),trim($_POST['address']??''),$_POST['admission_date']?:date('Y-m-d')]);$sid=(int)$pdo->lastInsertId();
   $pdo->commit();audit($pdo,'create','students',$sid,'Registration number '.$admissionNo);flash('success','Student registered. Admission/registration number: '.$admissionNo.' | Username: '.$username.' | First password: '.$temp);redirect('students.php');
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getCode()==='23000'?'A unique value already exists. Please try again.':'Could not register student.';}
}
$classes=$pdo->query("SELECT * FROM classes WHERE active=1 ORDER BY FIELD(name,'JSS1','JSS2','JSS3','SSS1','SSS2','SSS3'),section")->fetchAll();$students=$pdo->query("SELECT s.*,c.name class_name,c.section,u.username FROM students s LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN users u ON u.id=s.user_id ORDER BY s.id DESC LIMIT 200")->fetchAll();$success=flash('success');
?><div class="d-flex justify-content-between mb-3"><h2>Student Registration</h2></div><?php if($success): ?><div class="alert alert-success"><strong>Save these credentials securely:</strong><br><?=e($success)?></div><?php endif;?><?php if(!empty($error)): ?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="alert alert-info">The system generates a unique Nigerian-school-style registration number using your configured school code, year and sequence. There is no single national format.</div>
<div class="card p-4 mb-4"><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="col-md-3"><label>Surname</label><input class="form-control" name="surname" required></div><div class="col-md-3"><label>First name</label><input class="form-control" name="firstname" required></div><div class="col-md-3"><label>Other name</label><input class="form-control" name="othername"></div><div class="col-md-3"><label>Email</label><input class="form-control" type="email" name="email"></div><div class="col-md-2"><label>Gender</label><select class="form-select" name="gender"><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></div><div class="col-md-3"><label>Date of birth</label><input type="date" class="form-control" name="dob"></div><div class="col-md-3"><label>Class</label><select class="form-select" name="class_id"><option value="">Unassigned</option><?php foreach($classes as $c): ?><option value="<?=$c['id']?>"><?=e($c['name'].' '.$c['section'])?></option><?php endforeach;?></select></div><div class="col-md-4"><label>Phone</label><input class="form-control" name="phone"></div><div class="col-md-6"><label>Address</label><textarea class="form-control" name="address"></textarea></div><div class="col-md-3"><label>Admission date</label><input type="date" class="form-control" name="admission_date" value="<?=date('Y-m-d')?>"></div><div class="col-12"><button class="btn btn-success">Register student & generate first password</button></div></form></div>
<div class="card p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Registration No.</th><th>Name</th><th>Username</th><th>Class</th><th>Status</th></tr></thead><tbody><?php foreach($students as $s): ?><tr><td><?=e($s['admission_no'])?></td><td><?=e(trim($s['surname'].' '.$s['firstname'].' '.$s['othername']))?></td><td><?=e($s['username'])?></td><td><?=e(trim(($s['class_name']??'').' '.($s['section']??'')))?></td><td><?=e($s['status'])?></td></tr><?php endforeach;?></tbody></table></div></div><?php require __DIR__.'/../includes/footer.php';
